drop table if exists fifa18;
create table fifa18(
    Wage numeric,
    Value numeric,
    Name varchar(300),
    Age numeric,
    Photo varchar(1000),
    Nationality varchar(50),
    Flag varchar(1000),
    Overall numeric,
    Potential numeric,
    Club varchar(100),
    "Club Logo" varchar(1000),
    Special numeric,
    Acceleration numeric,
    Aggression numeric,
    Agility numeric,
    Balance numeric,
    "Ball control" numeric,
    Composure numeric,
    Crossing numeric,
    Curve numeric,
    Dribbling numeric,
    Finishing numeric,
    "Free kick accuracy" numeric,
    "GK diving" numeric,
    "GK handling" numeric,
    "GK kicking" numeric,
    "GK positioning" numeric,
    "GK reflexes" numeric,
    "Heading accuracy" numeric,
    Interceptions numeric,
    Jumping numeric,
    "Long passing" numeric,
    "Long shots" numeric,
    Marking numeric,
    Penalties numeric,
    Positioning numeric,
    Reactions numeric,
    "Short passing" numeric,
    "Shot power" numeric,
    "Sliding tackle" numeric,
    "Sprint speed" numeric,
    Stamina numeric,
    "Standing tackle" numeric,
    Strength numeric,
    Vision numeric,
    Volleys numeric,
    CAM numeric,
    CB numeric,
    CDM numeric,
    CF numeric,
    CM numeric,
    ID numeric,
    LAM numeric,
    LB numeric,
    LCB numeric,
    LCM numeric,
    LDM numeric,
    LF numeric,
    LM numeric,
    LS numeric,
    LW numeric,
    LWB numeric,
    "Preferred Positions" varchar(30),
    RAM numeric,
    RB numeric,
    RCB numeric,
    RCM numeric,
    RDM numeric,
    RF numeric,
    RM numeric,
    RS numeric,
    RW numeric,
    RWB numeric,
    ST numeric
);
COPY fifa18
FROM '/etc/data/fifa18.csv' CSV HEADER