COPY customer
FROM '/etc/data/customer.tbl' WITH DELIMITER AS '|';
COPY lineitem
FROM '/etc/data/lineitem.tbl' WITH DELIMITER AS '|';
COPY nation
FROM '/etc/data/nation.tbl' WITH DELIMITER AS '|';
COPY orders
FROM '/etc/data/orders.tbl' WITH DELIMITER AS '|';
COPY part
FROM '/etc/data/part.tbl' WITH DELIMITER AS '|';
COPY partsupp
FROM '/etc/data/partsupp.tbl' WITH DELIMITER AS '|';
COPY region
FROM '/etc/data/region.tbl' WITH DELIMITER AS '|';
COPY supplier
FROM '/etc/data/supplier.tbl' WITH DELIMITER AS '|';
ALTER TABLE REGION
ADD PRIMARY KEY (R_REGIONKEY);
ALTER TABLE NATION
ADD PRIMARY KEY (N_NATIONKEY);
ALTER TABLE CUSTOMER
ADD PRIMARY KEY (C_CUSTKEY);
ALTER TABLE SUPPLIER
ADD PRIMARY KEY (S_SUPPKEY);
ALTER TABLE PART
ADD PRIMARY KEY (P_PARTKEY);
ALTER TABLE PARTSUPP
ADD PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY);
ALTER TABLE ORDERS
ADD PRIMARY KEY (O_ORDERKEY);
ALTER TABLE LINEITEM
ADD PRIMARY KEY (L_ORDERKEY, L_LINENUMBER);
ALTER TABLE NATION
ADD FOREIGN KEY (N_REGIONKEY) REFERENCES REGION(R_REGIONKEY);
ALTER TABLE SUPPLIER
ADD FOREIGN KEY (S_NATIONKEY) REFERENCES NATION(N_NATIONKEY);
ALTER TABLE CUSTOMER
ADD FOREIGN KEY (C_NATIONKEY) REFERENCES NATION(N_NATIONKEY);
ALTER TABLE PARTSUPP
ADD FOREIGN KEY (PS_SUPPKEY) REFERENCES SUPPLIER(S_SUPPKEY);
ALTER TABLE PARTSUPP
ADD FOREIGN KEY (PS_PARTKEY) REFERENCES PART(P_PARTKEY);
ALTER TABLE ORDERS
ADD FOREIGN KEY (O_CUSTKEY) REFERENCES CUSTOMER(C_CUSTKEY);
ALTER TABLE LINEITEM
ADD FOREIGN KEY (L_ORDERKEY) REFERENCES ORDERS(O_ORDERKEY);
ALTER TABLE LINEITEM
ADD FOREIGN KEY (L_PARTKEY, L_SUPPKEY) REFERENCES PARTSUPP(PS_PARTKEY, PS_SUPPKEY);